export const DE_COMPONENTS_GRID_VIEW = 'grid-view';
export const DE_COMPONENTS_LIST_VIEW = 'list-view';

export const DE_COMPONENT_INSTALLATION_STATUS_CREATED = 'INSTALL_CREATED';
export const DE_COMPONENT_INSTALLATION_STATUS_IN_PROGRESS = 'INSTALL_IN_PROGRESS';
export const DE_COMPONENT_INSTALLATION_STATUS_COMPLETED = 'INSTALL_COMPLETED';
export const DE_COMPONENT_INSTALLATION_STATUS_ERROR = 'INSTALL_ERROR';

export const DE_COMPONENT_UNINSTALLATION_STATUS_CREATED = 'UNINSTALL_CREATED';
export const DE_COMPONENT_UNINSTALLATION_STATUS_IN_PROGRESS = 'UNINSTALL_IN_PROGRESS';
export const DE_COMPONENT_UNINSTALLATION_STATUS_COMPLETED = 'UNINSTALL_COMPLETED';
export const DE_COMPONENT_UNINSTALLATION_STATUS_ERROR = 'UNINSTALL_ERROR';
