export const DE_COMPONENTS_GRID_VIEW = 'grid-view';
export const DE_COMPONENTS_LIST_VIEW = 'list-view';

export const DE_COMPONENT_INSTALLATION_STATUS_CREATED = 'CREATED';
export const DE_COMPONENT_INSTALLATION_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const DE_COMPONENT_INSTALLATION_STATUS_COMPLETED = 'COMPLETED';
export const DE_COMPONENT_INSTALLATION_STATUS_ERROR = 'ERROR';
export const DE_COMPONENT_UNINSTALLATION_STATUS_IN_PROGRESS = 'IN_PROGRESS_UNINSTALL';
