const fs = require('fs-extra');
const path = require('path');

const Log = require('@entando/log');


const APPS_JS_FILE_PATH = path.resolve('./src/entando-apps.js');

// -----------------------------------------------------------------------------
// ----------------------- Import JS file creation -----------------------------
// -----------------------------------------------------------------------------

const createAppsImportFile = (app, id, packageName) => {
  Log.section('Creating app import file');

  let fileText = '';

  fileText += '// -----------------------------------------------------------------------------\n';
  fileText += '// WARNING: this file is automatically generated by the app-install script.\n';
  fileText += '//          Any change to this file will be overwritten when adding apps.\n';
  fileText += '// -----------------------------------------------------------------------------\n\n';

  fileText += `import ${id} from '${packageName}/dist/babel';\n`;
  fileText += `import '${packageName}/dist/css/index.css';\n`;
  fileText += '\n\n';

  fileText += 'const apps = [];';
  fileText += '\n\n';

  fileText += `apps.push(${id});\n`;
  fileText += '\n\n';

  fileText += 'export default apps;\n';

  return new Promise((resolve, reject) => {
    fs.writeFile(APPS_JS_FILE_PATH, fileText, 'utf8', (err) => {
      if (err) {
        Log.error(`Error writing file: ${APPS_JS_FILE_PATH}`, err);
        reject(err);
      } else {
        Log.success(`Imports file created: ${APPS_JS_FILE_PATH}`);
        resolve();
      }
    });
  });
};

module.exports = createAppsImportFile;
