const fs = require('fs-extra'),
  path = require('path'),
  chalk = require('chalk'),

  Log = require('./Log.js');


const IMPORTS_JS_FILE_PATH = path.resolve('./src/entando-plugins.js');



// -----------------------------------------------------------------------------
// ----------------------- Import JS file creation -----------------------------
// -----------------------------------------------------------------------------

function createPluginsImportFile(pluginDefs) {

  Log.section('Creating plugin import file');

  let fileText = '';

  fileText += '// -----------------------------------------------------------------------------\n';
  fileText += '// WARNING: this file is automatically generated by the import-plugins script.\n';
  fileText += '//          Any change to this file will be overwritten when importing plugins.\n';
  fileText += '// -----------------------------------------------------------------------------\n\n';

  if (pluginDefs.length) {
    pluginDefs.forEach((plugin, i) => {
      fileText += "import plugin" + i + " from '" + plugin.name + "/pluginBuild/static/js/main';\n";
    });

    fileText += "\n\n";

    pluginDefs.forEach((plugin, i) => {
      fileText += "import '" + plugin.name + "/pluginBuild/static/css/main.css';\n";
    });

    fileText += "\n\n";
    fileText += "const plugins = [];";
    fileText += "\n\n";

    pluginDefs.forEach((plugin, i) => {
      fileText += "plugins.push(plugin" + i + ");\n";
    });

    fileText += "\n\n";
    fileText += "export default plugins;\n";

  } else {
    fileText += "const plugins = [];\n";
    fileText += "export default plugins;\n";
  }


  return new Promise((resolve, reject) => {
    fs.writeFile(IMPORTS_JS_FILE_PATH, fileText, 'utf8', (err) => {
      if (err) {
        Log.error('Error writing file: ' + IMPORTS_JS_FILE_PATH, err);
        reject(err);
      } else {
        Log.success('Imports file created: ' + IMPORTS_JS_FILE_PATH);
        resolve();
      }
    });
  });

}

module.exports = createPluginsImportFile;
