// -----------------------------------------------------------------------------
// WARNING: this file is automatically generated by the app-install script.
//          Any change to this file will be overwritten when adding apps.
// -----------------------------------------------------------------------------

import cms from '@entando/cms/dist/babel';


const apps = [];

apps.push(cms);


export default apps;
