// -----------------------------------------------------------------------------
// WARNING: this file is automatically generated by the import-plugins script.
//          Any change to this file will be overwritten when importing plugins.
// -----------------------------------------------------------------------------

import plugin0 from 'entando-plugin-dashboard/dist';


import 'entando-plugin-dashboard/dist/index.css';


const plugins = [];

plugins.push(plugin0);


export default plugins;
